// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VaruosadAPI.Data;

#nullable disable

namespace VaruosadAPI.Migrations
{
    [DbContext(typeof(SparePartsContext))]
    [Migration("20230327143859_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("VaruosadAPI.Models.SparePartsModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<float?>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("WareHouse5")
                        .HasColumnType("TEXT");

                    b.Property<string>("Warehouse1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Warehouse2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Warehouse3")
                        .HasColumnType("TEXT");

                    b.Property<string>("Warehouse4")
                        .HasColumnType("TEXT");

                    b.Property<string>("Warehouse6")
                        .HasColumnType("TEXT");

                    b.Property<string>("WithoutVAT")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SparePartsModel");
                });
#pragma warning restore 612, 618
        }
    }
}
